# Generated by Django 5.1.2 on 2026-08-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspections/')),
                ('caption', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('entry', "Fiche d'entrée"), ('exit', 'Fiche de sortie')], max_length=10)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('mileage_at_inspection', models.IntegerField()),
                ('fuel_level', models.IntegerField()),
                ('condition_score', models.IntegerField()),
                ('checklist', models.JSONField(default=dict)),
                ('issues', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Inspection véhicule',
                'verbose_name_plural': 'Inspections véhicules',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
