# Generated by Django 5.1.2 on 2026-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dispute_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_type',
            field=models.CharField(choices=[('none', 'Sans chauffeur'), ('internal', 'Chauffeur AutoLink'), ('owner', 'Chauffeur du propriétaire')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('confirmed', 'Confirmé'), ('active', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('disputed', 'Litige')], default='pending', max_length=20),
        ),
    ]
