# Generated by Django 5.1.2 on 2026-09-24 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_dispute_opened_at_booking_dispute_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Caution de garantie bloquée chez le client pendant la location.', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='Dégressivité longue durée : -5 % dès 7 jours, -10 % dès 30 jours.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
