# Generated by Django 5.2.5 on 2026-10-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_deposit_amount_booking_discount_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='intermediary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='intermediary_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Commission de l'intermédiaire — prélevée sur la part AutoLink.", max_digits=12),
        ),
    ]
