# Generated by Django 5.2.5 on 2026-10-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_logincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Commission intermédiaire en % du montant location — prélevée sur la part AutoLink.', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text="Code parrain de l'intermédiaire (ex. AL-4F2K9B).", max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text="Intermédiaire dont le code a été utilisé à l'inscription.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('OWNER', 'Propriétaire'), ('DRIVER', 'Chauffeur'), ('ADMIN', 'Administrateur'), ('CONTROLLER', 'Contrôleur'), ('INTERMEDIARY', 'Intermédiaire')], default='CLIENT', max_length=20),
        ),
    ]
