# Generated by Django 4.2.7 on 2026-10-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_intermediary_booking_intermediary_commission'),
        ('users', '0005_user_commission_rate_user_referral_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default='0.50', help_text='Part AutoLink sur chaque location (fraction, ex. 0.50 = 50 %).', max_digits=4)),
                ('intermediary_default_rate', models.DecimalField(decimal_places=2, default='5.00', help_text='Taux par défaut des nouveaux intermédiaires (en %).', max_digits=5)),
                ('driver_service_price', models.DecimalField(decimal_places=2, default='75000', help_text='Forfait du service recrutement/formation chauffeur (FCFA).', max_digits=10)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres de la plateforme',
                'verbose_name_plural': 'Paramètres de la plateforme',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bookings.booking')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['created_at'],
            },
        ),
    ]
