# Generated by Django 5.1.2 on 2026-08-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('review', 'En examen'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('experience_years', models.IntegerField(default=0)),
                ('has_valid_license', models.BooleanField(default=False)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('license_document', models.ImageField(blank=True, null=True, upload_to='drivers/licenses/')),
                ('has_clean_criminal_record', models.BooleanField(default=False)),
                ('criminal_record_document', models.ImageField(blank=True, null=True, upload_to='drivers/criminal/')),
                ('has_medical_certificate', models.BooleanField(default=False)),
                ('medical_certificate_document', models.ImageField(blank=True, null=True, upload_to='drivers/medical/')),
                ('driving_test_passed', models.BooleanField(default=False)),
                ('driving_test_score', models.IntegerField(blank=True, null=True)),
                ('training_completed', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Candidature chauffeur',
                'verbose_name_plural': 'Candidatures chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.IntegerField(default=0)),
                ('total_trips', models.IntegerField(default=0)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acceptance_rate', models.IntegerField(default=100)),
                ('on_time_rate', models.IntegerField(default=100)),
                ('is_online', models.BooleanField(default=False)),
                ('certified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil chauffeur',
            },
        ),
    ]
