# Generated by Django 5.2.5 on 2026-10-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers_count', models.IntegerField(default=1)),
                ('city', models.CharField(default='Douala', max_length=50)),
                ('requirements', models.TextField(blank=True, help_text='Critères particuliers du propriétaire (expérience, zone, type de véhicule…)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('recruiting', 'Recrutement en cours'), ('training', 'Formation en cours'), ('delivered', 'Chauffeur transmis'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=75000, help_text='Forfait par chauffeur recruté et formé (FCFA).', max_digits=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_service_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_driver_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de service chauffeur',
                'verbose_name_plural': 'Demandes de service chauffeur',
                'ordering': ['-created_at'],
            },
        ),
    ]
