# Generated by Django 5.1.2 on 2026-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_available',
            field=models.BooleanField(default=True, help_text='Le propriétaire peut fournir son propre chauffeur avec ce véhicule.'),
        ),
    ]
