# Generated by Django 5.1.2 on 2026-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_driver_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.CharField(default='Douala', help_text='Ville de mise à disposition — coefficient tarifaire local.', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Caution de garantie demandée au client (bloquée pendant la location).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='extra_km_rate',
            field=models.IntegerField(blank=True, help_text='Tarif du kilomètre au-delà du forfait (FCFA).', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='km_included_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valeur marchande estimée du véhicule (FCFA) — socle du prix de location.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tier',
            field=models.CharField(choices=[('basic', 'Économique'), ('standard', 'Intermédiaire'), ('premium', 'Premium'), ('gold', 'Luxe'), ('collection', 'Super Luxe')], default='standard', max_length=20),
        ),
    ]
