# Generated by Django 5.1.2 on 2026-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_city_vehicle_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_url',
            field=models.URLField(blank=True, help_text='Photo réelle du modèle (vignette allégée Wikimedia Commons).', max_length=500),
        ),
    ]
