# Generated by Django 5.1.2 on 2026-09-15 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('senbid', 'SenBid'), ('paybid', 'PayBid'), ('paypal', 'PayPal'), ('stripe', 'Stripe (Carte)'), ('wallet', 'Solde AutoLink')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='method',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('senbid', 'SenBid'), ('paybid', 'PayBid'), ('paypal', 'PayPal'), ('stripe', 'Stripe (Carte)'), ('wallet', 'Solde AutoLink')], max_length=20),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup', 'Rechargement'), ('debit', 'Débit (paiement)'), ('refund', 'Remboursement')], max_length=10)),
                ('method', models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('senbid', 'SenBid'), ('paybid', 'PayBid'), ('paypal', 'PayPal'), ('stripe', 'Stripe (Carte)'), ('wallet', 'Solde AutoLink')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction portefeuille',
                'ordering': ['-created_at'],
            },
        ),
    ]
