# Generated by Django 5.1.2 on 2026-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_method_alter_payout_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='escrow_status',
            field=models.CharField(choices=[('held', 'Caution bloquée'), ('released', 'Caution libérée (propriétaire payé)'), ('refunded', 'Caution remboursée au client'), ('disputed', 'Caution gelée (litige)')], default='held', max_length=20),
        ),
    ]
