# Generated by Django 5.1.2 on 2026-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_escrow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='deposit_status',
            field=models.CharField(choices=[('held', 'Caution bloquée'), ('released', 'Caution rendue au client'), ('forfeited', 'Caution versée au propriétaire')], default='held', max_length=20),
        ),
    ]
