# Generated by Django 5.1.2 on 2026-09-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_deposit_amount_payment_deposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='provider_ref',
            field=models.CharField(blank=True, help_text='ID session Stripe / commande PayPal', max_length=200),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Confirmée'), ('failed', 'Échouée')], default='completed', max_length=20),
        ),
    ]
